In [51]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [52]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
import warnings
warnings.filterwarnings ('ignore')

In [53]:
ds=pd.read_csv('abalone.csv')
ds

M  0.455  0.365  0.095   0.514  0.2245   0.101    0.15  15
0     M  0.350  0.265  0.090  0.2255  0.0995  0.0485  0.0700   7
1     F  0.530  0.420  0.135  0.6770  0.2565  0.1415  0.2100   9
2     M  0.440  0.365  0.125  0.5160  0.2155  0.1140  0.1550  10
3     I  0.330  0.255  0.080  0.2050  0.0895  0.0395  0.0550   7
4     I  0.425  0.300  0.095  0.3515  0.1410  0.0775  0.1200   8
...  ..    ...    ...    ...     ...     ...     ...     ...  ..
4171  F  0.565  0.450  0.165  0.8870  0.3700  0.2390  0.2490  11
4172  M  0.590  0.440  0.135  0.9660  0.4390  0.2145  0.2605  10
4173  M  0.600  0.475  0.205  1.1760  0.5255  0.2875  0.3080   9
4174  F  0.625  0.485  0.150  1.0945  0.5310  0.2610  0.2960  10
4175  M  0.710  0.555  0.195  1.9485  0.9455  0.3765  0.4950  12

[4176 rows x 9 columns]

In [54]:
ds=pd.read_csv('abalone.csv',names=range(0,9),header=0)

In [55]:
ds

0      1      2      3       4       5       6       7   8
0     M  0.350  0.265  0.090  0.2255  0.0995  0.0485  0.0700   7
1     F  0.530  0.420  0.135  0.6770  0.2565  0.1415  0.2100   9
2     M  0.440  0.365  0.125  0.5160  0.2155  0.1140  0.1550  10
3     I  0.330  0.255  0.080  0.2050  0.0895  0.0395  0.0550   7
4     I  0.425  0.300  0.095  0.3515  0.1410  0.0775  0.1200   8
...  ..    ...    ...    ...     ...     ...     ...     ...  ..
4171  F  0.565  0.450  0.165  0.8870  0.3700  0.2390  0.2490  11
4172  M  0.590  0.440  0.135  0.9660  0.4390  0.2145  0.2605  10
4173  M  0.600  0.475  0.205  1.1760  0.5255  0.2875  0.3080   9
4174  F  0.625  0.485  0.150  1.0945  0.5310  0.2610  0.2960  10
4175  M  0.710  0.555  0.195  1.9485  0.9455  0.3765  0.4950  12

[4176 rows x 9 columns]

In [56]:
ds.describe()

1            2            3            4           5  \
count  4176.000000  4176.000000  4176.000000  4176.000000  4176.00000   
mean      0.524009     0.407892     0.139527     0.828818     0.35940   
std       0.120103     0.099250     0.041826     0.490424     0.22198   
min       0.075000     0.055000     0.000000     0.002000     0.00100   
25%       0.450000     0.350000     0.115000     0.441500     0.18600   
50%       0.545000     0.425000     0.140000     0.799750     0.33600   
75%       0.615000     0.480000     0.165000     1.153250     0.50200   
max       0.815000     0.650000     1.130000     2.825500     1.48800   

                 6            7            8  
count  4176.000000  4176.000000  4176.000000  
mean      0.180613     0.238852     9.932471  
std       0.109620     0.139213     3.223601  
min       0.000500     0.001500     1.000000  
25%       0.093375     0.130000     8.000000  
50%       0.171000     0.234000     9.000000  
75%       0.253000     0.329000    11.000000  
max       0.760000     1.005000    29.000000

In [57]:
ds.isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
dtype: int64

In [58]:
ds.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
5    float64
6    float64
7    float64
8      int64
dtype: object

In [59]:
from sklearn.preprocessing import LabelEncoder

In [60]:
ds[0]=le.fit_transform(ds[0])

NameError: name 'le' is not defined

In [61]:
ds

0      1      2      3       4       5       6       7   8
0     M  0.350  0.265  0.090  0.2255  0.0995  0.0485  0.0700   7
1     F  0.530  0.420  0.135  0.6770  0.2565  0.1415  0.2100   9
2     M  0.440  0.365  0.125  0.5160  0.2155  0.1140  0.1550  10
3     I  0.330  0.255  0.080  0.2050  0.0895  0.0395  0.0550   7
4     I  0.425  0.300  0.095  0.3515  0.1410  0.0775  0.1200   8
...  ..    ...    ...    ...     ...     ...     ...     ...  ..
4171  F  0.565  0.450  0.165  0.8870  0.3700  0.2390  0.2490  11
4172  M  0.590  0.440  0.135  0.9660  0.4390  0.2145  0.2605  10
4173  M  0.600  0.475  0.205  1.1760  0.5255  0.2875  0.3080   9
4174  F  0.625  0.485  0.150  1.0945  0.5310  0.2610  0.2960  10
4175  M  0.710  0.555  0.195  1.9485  0.9455  0.3765  0.4950  12

[4176 rows x 9 columns]

In [62]:
x=ds.iloc[:,1:-1]
y=ds.iloc[:,-1]

In [63]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.22,random_state=46)

In [64]:
mnb=MultinomialNB()
mnb.fit(x_train,y_train)
predmnb=mnb.predict(x_test)
print(accuracy_score(y_test,predmnb))
print(confusion_matrix(y_test,predmnb))
print(classification_report(y_test,predmnb))

0.16648531011969533
[[  0   0   0   0   0   0   2   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0  15   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0  23   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0  61   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0  74   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0 114   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0 152   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0 148   1   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0 106   1   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0  66   1   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0  50   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 

In [65]:
svc=SVC(kernel='rbf')
svc.fit(x_train,y_train)
predsvc=svc.predict(x_test)
print(accuracy_score(y_test,predsvc))
print(confusion_matrix(y_test,predsvc))
print(classification_report(y_test,predsvc))

0.27094668117519044
[[ 0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 11  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  9 11  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  7 14 35  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1 17 38 13  4  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  4 17 51 37  5  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  3 15 33 59 34  8  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1 11 27 48 46 16  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  3  9 28 34 32  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  1  9 15 26 15  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  9 15 18  8  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  3  3 11  5  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  2  6 10  3  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  2 10  2  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  8  9  6  0  0  0  0  0  0  0  0  0 

In [66]:
dtc=DecisionTreeClassifier()
dtc.fit(x_train,y_train)
dtc.score(x_train,y_train)
preddtc=dtc.predict(x_test)
print(accuracy_score(y_test,preddtc))
print(confusion_matrix(y_test,preddtc))
print(classification_report(y_test,preddtc))

0.17519042437431992
[[ 0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  1  9  2  0  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  4  7  4  5  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  2  6 16 17 12  3  3  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  7 19 23  8  4  4  8  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  7 15 21 28 24  8  4  3  1  1  1  0  0  0  0  0  0  0]
 [ 0  0  0  6 14 25 32 29 19 10  4  2  5  2  0  2  0  1  1  0  0]
 [ 0  0  0  3 14 14 36 25 22  9 11  5  5  1  0  3  0  1  0  0  0]
 [ 0  0  0  1  5 14 16 25 16 13  2  4  6  2  1  0  1  1  0  0  0]
 [ 0  0  0  0  4  4  8 17 10  7  2  4  4  1  1  0  1  0  2  0  2]
 [ 0  0  0  0  1  5  4  6  9  7  4  4  0  3  3  1  3  0  0  0  0]
 [ 0  0  0  0  0  0  2  2  6  3  3  3  0  3  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  3  2  3  2  2  0  5  0  0  2  0  1  0  0  0]
 [ 0  0  0  0  0  2  0  2  2  3  3  0  1  0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  2  3  1  2  5  5  2  2  0  0  1  0 

In [67]:
from sklearn.neighbors import KNeighborsClassifier
dtc=KNeighborsClassifier()
dtc.fit(x_train,y_train)
dtc.score(x_train,y_train)
preddtc=dtc.predict(x_test)
print(accuracy_score(y_test,preddtc))
print(confusion_matrix(y_test,preddtc))
print(classification_report(y_test,preddtc))

0.22850924918389554
[[ 0  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 5  3  3  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 2  3 10  4  3  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  3  5 23 25  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  9 23 26  7  5  3  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  5 30 33 31 11  2  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  8 16 27 44 39 16  1  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  3  9 25 39 40 21  6  4  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  2  5 11 25 33 22  2  4  0  1  1  0  0  0  1  0  0  0]
 [ 0  0  0  1  4  4 12 16 16  5  5  1  1  1  0  0  1  0  0  0  0]
 [ 0  0  0  0  3  7  7 14 11  2  3  1  1  0  1  0  0  0  0  0  0]
 [ 0  0  0  0  1  3  4  4  2  2  2  1  0  3  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  5  9  0  0  2  3  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  1  1  4  3  0  2  1  0  0  1  0  1  0  0  0  0]
 [ 0  0  0  0  0  4  0  5  3  5  1  2  3  1  0  0  0  0 

In [68]:
def svmkernel(ker):
    svc=SVC(kernel=ker)
    svc.fit(x_train,y_train)
    predsvc=svc.predict(x_test)
    print(accuracy_score(y_test,predsvc))
    print(confusion_matrix(y_test,predsvc))
    print(classification_report(y_test,predsvc))

In [69]:
svmkernel('poly')

0.264417845484222
[[ 0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 15  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 20  0  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 17  0 42  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 11  0 49 10  3  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  3  0 25 48 35  3  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  0 19 36 68 23  4  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0 14 29 52 43  8  0  2  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  3 12 30 45 14  0  2  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  2  9 18 28  8  0  1  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  8 13 21  6  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  1 12  2  0  1  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  4  3 12  1  0  0  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 12  1  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  3  3 11  1  1  1  1  0  3  0  0  0  0  0

In [70]:
svmkernel('rbf')

0.27094668117519044
[[ 0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 11  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  9 11  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  7 14 35  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1 17 38 13  4  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  4 17 51 37  5  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  3 15 33 59 34  8  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1 11 27 48 46 16  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  3  9 28 34 32  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  1  9 15 26 15  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  9 15 18  8  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  3  3 11  5  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  2  6 10  3  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  2 10  2  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  8  9  6  0  0  0  0  0  0  0  0  0 

In [71]:
svmkernel('linear')

0.2611534276387378
[[ 0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 12  0  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 16  0  7  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 11  0 48  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  5  0 53 11  4  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0 25 47 37  4  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0 19 31 62 39  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0 13 25 48 62  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  4  9 30 64  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  2  9 17 39  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  8 13 28  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  3  3 16  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  3  4 14  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 14  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  5 18  0  0  0  0  0  0  0  0  0  0  

In [72]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,mean_absolute_error

In [73]:
lm=LinearRegression()

In [74]:
lm.fit(x_train,y_train)
lm.score(x_train,y_train)

0.5209438768861975

In [75]:
sns.pairplot(ds)

Error in callback <function flush_figures at 0x0000017254E609D8> (for post_execute):


KeyboardInterrupt: 

In [98]:
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor(n_estimators=140,random_state=55)
rf.fit(x_train,y_train)
print(rf.score(x_train,y_train))
predrf=rf.predict(x_test)
print(mean_squared_error(y_test,predrf))
print(mean_absolute_error(y_test,predrf))


0.9351431074410776
4.338130399058426
1.5243587750660654


In [94]:
from sklearn.ensemble import AdaBoostRegressor
ad=AdaBoostRegressor(n_estimators=5)
ad.fit(x_train,y_train)
print(ad.score(x_train,y_train))
ad_pred=ad.predict(x_test)
print(mean_squared_error(y_test,ad_pred))
print(mean_absolute_error(y_test,ad_pred))


0.45510868631697965
5.48941422623749
1.8296411904827032
